//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPeluquería.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoPeluquería.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actualizar__2_ {
            get {
                object obj = ResourceManager.GetObject("actualizar (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actualizar_flecha {
            get {
                object obj = ResourceManager.GetObject("actualizar-flecha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agregar__2_ {
            get {
                object obj = ResourceManager.GetObject("agregar (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agregar_tiempo {
            get {
                object obj = ResourceManager.GetObject("agregar-tiempo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agregar_usuario {
            get {
                object obj = ResourceManager.GetObject("agregar-usuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banco {
            get {
                object obj = ResourceManager.GetObject("banco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap basura__2_ {
            get {
                object obj = ResourceManager.GetObject("basura (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap busqueda {
            get {
                object obj = ResourceManager.GetObject("busqueda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caja__1_ {
            get {
                object obj = ResourceManager.GetObject("caja (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap carrito_de_compra_anadir {
            get {
                object obj = ResourceManager.GetObject("carrito-de-compra-anadir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cejas {
            get {
                object obj = ResourceManager.GetObject("cejas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap configuraciones {
            get {
                object obj = ResourceManager.GetObject("configuraciones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corte_americano_baixo_low_disfarcado {
            get {
                object obj = ResourceManager.GetObject("corte_americano_baixo_low_disfarcado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corte_clasico {
            get {
                object obj = ResourceManager.GetObject("corte clasico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cortes_de_pelo_con_lineas_y_cejas_simple_500x621 {
            get {
                object obj = ResourceManager.GetObject("cortes_de_pelo_con_lineas_y_cejas_simple_500x621", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cruz {
            get {
                object obj = ResourceManager.GetObject("cruz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap degrade {
            get {
                object obj = ResourceManager.GetObject("degrade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dibujo {
            get {
                object obj = ResourceManager.GetObject("dibujo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editar__2_ {
            get {
                object obj = ResourceManager.GetObject("editar (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap espuma1 {
            get {
                object obj = ResourceManager.GetObject("espuma1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap frente {
            get {
                object obj = ResourceManager.GetObject("frente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fuego__8_ {
            get {
                object obj = ResourceManager.GetObject("fuego (8)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gira_a_la_derecha_f5_negro {
            get {
                object obj = ResourceManager.GetObject("gira-a-la-derecha f5 negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hqdefault {
            get {
                object obj = ResourceManager.GetObject("hqdefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lavado {
            get {
                object obj = ResourceManager.GetObject("lavado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a async function NumNotExiting()
        ///{
        ///    Home = document.querySelector(&apos;div[class=&quot;_3ev9-&quot;]&apos;);
        ///    Error0 = Home.querySelector(&apos;div[class=&quot;_3J6wB&quot;]&apos;);
        ///    Error1 = Error0.querySelector(&apos;div[class=&quot;nne8e&quot;]&apos;);
        ///    ErrorMSJ = Error1.querySelector(&apos;div[class=&quot;_2Nr6U&quot;]&apos;);
        ///
        ///    if(ErrorMSJ)
        ///    {
        ///        console.log(&quot;Se encontro un error.&quot;);
        ///    }
        ///    else
        ///    {
        ///        console.log(&quot;No se encontro nada.&quot;);
        ///    }
        ///    return true;
        ///}
        ///
        /////NumNotExiting();
        ///
        ///
        ///.
        /// </summary>
        internal static string MensajeDeError {
            get {
                return ResourceManager.GetString("MensajeDeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap modo_retrato {
            get {
                object obj = ResourceManager.GetObject("modo-retrato", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monedas {
            get {
                object obj = ResourceManager.GetObject("monedas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ojo {
            get {
                object obj = ResourceManager.GetObject("ojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ojos_cruzados__1_ {
            get {
                object obj = ResourceManager.GetObject("ojos-cruzados (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_plus_and_minus_signs_symbol_computer_icons_symbol_miscellaneous_logo_cross {
            get {
                object obj = ResourceManager.GetObject("png_transparent_plus_and_minus_signs_symbol_computer_icons_symbol_miscellaneous_l" +
                        "ogo_cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a async function DetectarInicio() {
        ///    Carga = document.querySelector(&quot;#app &gt; div &gt; div &gt; div.g0rxnol2.lk9bdx0e.d9lyu8cj.qlylaf53.d4g41f7d &gt; progress&quot;);
        ///    Home = document.querySelector(&quot;#side &gt; div.uwk68 &gt; div &gt; div &gt; div._16C8p &gt; div &gt; div._13NKt.copyable-text.selectable-text&quot;);
        ///    Exito = false;
        ///
        ///    if (Carga) {
        ///        console.log(&quot;[Cargando]&quot;);
        ///    }
        ///    else if (Home) {
        ///        console.log(&quot;[EXITO]&quot;);
        ///        Exito = true;
        ///    }
        ///    return Exito;
        ///}
        ///
        ///DetectarInicio();.
        /// </summary>
        internal static string ProcAndHome {
            get {
                return ResourceManager.GetString("ProcAndHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quitar_usuario {
            get {
                object obj = ResourceManager.GetObject("quitar-usuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seleccione {
            get {
                object obj = ResourceManager.GetObject("seleccione", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a async function enviarScript(scriptText){
        ///    const lines = scriptText.split(/[\n\t]+/);
        ///    textarea = document.querySelector(&quot;#main &gt; footer &gt; div._2BU3P.tm2tP.copyable-area &gt; div &gt; span:nth-child(2) &gt; div &gt; div._2lMWa &gt; div.p3_M1 &gt; div &gt; div.fd365im1.to2l77zo.bbv8nyr4.mwp4sxku.gfz4du6o.ag5g9lrv&quot;);
        ///
        ///    if(Chats)
        ///    {
        ///        console.log(&quot;WhatsApp Web iniciado.&quot;);
        ///        if(main)
        ///        {
        ///            console.log(&quot;Chat Abierto.&quot;);
        ///            for(const line of lines){            
        ///              [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Sendmsj {
            get {
                return ResourceManager.GetString("Sendmsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tarjeta_de_credito {
            get {
                object obj = ResourceManager.GetObject("tarjeta-de-credito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tiempo_pasado {
            get {
                object obj = ResourceManager.GetObject("tiempo-pasado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap usd_circulo {
            get {
                object obj = ResourceManager.GetObject("usd-circulo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a function VerificarInicio()
        ///{
        ///    Home = document.querySelector(&apos;div[class=&quot;_3ArsE&quot;]&apos;);   
        ///    Chats = Home.querySelector(&apos;div[class=&quot;ldL67 _2i3T7 _1cpSb&quot;]&apos;);
        ///    HomeWhats = Home.querySelector(&apos;div[class=&quot;ldL67 _3sh5K&quot;]&apos;);
        ///    HomeWhats1 = HomeWhats.querySelector(&apos;div[class=&quot;zaKsw&quot;]&apos;);
        ///
        ///    if(Chats)
        ///    {
        ///        console.log(&quot;Listo&quot;);
        ///    }
        ///    else
        ///    {
        ///        console.log(&quot;NO&quot;);
        ///    }
        ///    return true;
        ///}
        ///
        ///VerificarInicio();.
        /// </summary>
        internal static string VerificacionHomeWhatsApp {
            get {
                return ResourceManager.GetString("VerificacionHomeWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a async function Login() {
        ///    Login = document.querySelector(&quot;#app &gt; div &gt; div &gt; div.landing-window &gt; div.landing-main &gt; div &gt; div._2WuPw&quot;);
        ///
        ///    if (Login) {
        ///        console.log(&quot;[/lobby]&quot;);
        ///    }
        ///    else {
        ///        console.log(&quot;[/not lobby]&quot;);
        ///    }
        ///}
        ///Login().
        /// </summary>
        internal static string VeriLobby {
            get {
                return ResourceManager.GetString("VeriLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x {
            get {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_b {
            get {
                object obj = ResourceManager.GetObject("x b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
